# Generated by Django 4.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="payment",
            name="order_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("SUCCESS", "SUCCESS"), ("FAILED", "FAILED")],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payment_status_idx"),
        ),
    ]
