# Generated by Django 4.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ["product_sku"]},
        ),
        migrations.AlterField(
            model_name="inventory",
            name="product_id",
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="product_sku",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
